### ISSUE TITLE
listamos: non-ASCII character incorrectly set/used in plain text

### ISSUE THREAD

**Issue by djipi** [kyz/amostools#3]
non-ASCII characters are not set, or used, by the listamos tool.
By example, in the AMOS original source code, the word käyttöön is seen as kΣytt÷÷n in plain text.

**Comment by kyz** [comment]
While tokens are always ASCII, the strings, labels, variable names and comments in AMOS programs can be in any charset. `listamos` prints these without any conversion.

The charset in the source code is the programmer's choice, the Amiga supported many. The most common is ISO-8859-1. If you `listamos` to print in a particular charset, you can use the `iconv` program to change the charset, e.g. here I change from ISO-8859-1 to UTF8 which is what my terminal normally displays:

```bash
$ hd kayttoon.amos 
00000000  41 4d 4f 53 20 42 61 73  69 63 20 76 31 2e 33 20  |AMOS Basic v1.3 |
00000010  00 00 00 12 09 01 06 4a  00 0a 20 6b e4 79 74 74  |.......J.. k.ytt|
00000020  f6 f6 6e 20 00 00 41 6d  42 73 00 00              |..n ..AmBs..|
0000002c
$ listamos kayttoon.amos 
Rem k�ytt��n 
$ listamos kayttoon.amos | iconv -f iso-8859-1 -t utf8
Rem käyttöön 
```

I'm not sure what [mojibake](https://en.wikipedia.org/wiki/Mojibake) causes käyttöön to render as kΣytt÷÷n, I'd be interested to know. The closest I can get is to confuse iso-8859-1 as iso-8859-7 to get "kδyttφφn"

```bash
$ echo käyttöön | iconv -f utf8 -t iso-8859-1 | iconv -f iso-8859-7 -t utf8
kδyttφφn
```

**Comment by djipi** [comment]
Thank you for the feedback and the work-around.
I'm using an open source AMOS code from Finland. And I'm on Windows and not Amiga.
Using your solution is not a big issue but can you add it in the tool's Readme (or wherever you feel relevant), it may be useful for others.

**Comment by kyz** [comment]
I added a section to the README, thanks for reporting the issue and good luck with your Finnish AMOS code!
